import React from 'react'

const ItemsData = [
    {
      "id":"1",
      "name":"nombre1",
      "description":"descripcion1",
      "price":"10",
      "stock":"10"
    },
    {
        "id":"2",
        "name":"nombre2",
        "description":"descripcion2",
        "price":"10",
        "stock":"10"
      },
      {
        "id":"3",
        "name":"nombre3",
        "description":"descripcion3",
        "price":"10",
        "stock":"10"
      },
      {
        "id":"4",
        "name":"nombre4",
        "description":"descripcion4",
        "price":"10",
        "stock":"10"
      },
      {
        "id":"5",
        "name":"nombre5",
        "description":"descripcion5",
        "price":"10",
        "stock":"10"
      },
      {
        "id":"6",
        "name":"nombre6",
        "description":"descripcion6",
        "price":"10",
        "stock":"10"
      },
      {
        "id":"7",
        "name":"nombre7",
        "description":"descripcion7",
        "price":"10",
        "stock":"10"
      },
      {
        "id":"8",
        "name":"nombre8",
        "description":"descripcion8",
        "price":"10",
        "stock":"10"
      }  
]

export default ItemsData
